name: Deploy

on:
  push:
    # only deploy from main
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_MAIN }}
        port: ${{ secrets.HOST_PORT }}
        username: ${{ secrets.USERNAME_MAIN }}
        key: ${{ secrets.SSHKEY_MAIN }}
        script: |
          cd sionministry.org
          git pull origin main
